import React, { useEffect, useRef, useState } from "react";
import {
  AlertTriangle,
  ArrowRight,
  Brain,
  Check,
  CheckCircle2,
  Clock,
  Copy,
  Download,
  Flame,
  Globe,
  Lock,
  Receipt,
  RotateCcw,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Star,
  Terminal,
  Undo2,
  X,
  XCircle,
  Zap,
} from "lucide-react";
import PrivacyPage from "./pages/PrivacyPage.jsx";
import TermsPage from "./pages/TermsPage.jsx";
import DocsPage from "./pages/DocsPage.jsx";

/**
 * Supported AI sites.
 */
const PLATFORMS = [
  { id: "chatgpt", name: "ChatGPT", host: "chatgpt.com" },
  { id: "claude", name: "Claude", host: "claude.ai" },
  { id: "gemini", name: "Google Gemini", host: "gemini.google.com" },
  { id: "perplexity", name: "Perplexity", host: "perplexity.ai" },
];

/** Download packages generated by scripts/build-extension.js. */
const DOWNLOADS = {
  chrome: "/downloads/refinzi-chrome-v2.1.0.zip",
  firefox: "/downloads/refinzi-firefox-v2.1.0.zip",
  edge: "/downloads/refinzi-edge-v2.1.0.zip",
};

const DEMO_INPUT = "make a marketing plan for my b2b saas";

/** Output of the ⚡ Click (Better) engine. */
const BETTER_OUTPUT = `Develop a practical go-to-market strategy for B2B SaaS.

Define:
1. Ideal customer profile (ICP) & core buyer pain points.
2. Recommended market-entry approach & positioning against incumbents.
3. Highest-leverage acquisition channels (organic search, outbound, partnerships).
4. Phased 90-day execution roadmap and conversion KPIs.

Clearly state any operational assumptions where product context is unavailable.`;

/** Output of the 🧠 Hold (Expert) engine. */
const EXPERT_OUTPUT = `Execution Directive: Develop a 90-day go-to-market strategy for B2B SaaS

Scope & Architecture:
- Beachhead Segment: Mid-market B2B decision-makers with 30-90 day discovery cycles
- Value Proposition: Quantifiable ROI metrics and positioning against legacy alternatives
- Distribution Channels: Founder-led outbound, high-intent search, and strategic partner ecosystem
- Phased Milestones: 0-30 day validation, 30-60 day acquisition loops, 60-90 day scale
- Performance KPIs: Pipeline velocity, customer acquisition cost (CAC), and trial-to-paid conversion

Assumptions: Mid-market B2B buyer (stated in prompt as assumption).

---
[Out-of-Scope Strategic Observations]
(Advisory notes outside the locked deliverable scope):
• Audit downstream onboarding funnel friction before expanding paid acquisition spend.`;

/** Hold threshold — mirrors extension/src/ui/orb.ts (holdThresholdMs = 350). */
const HOLD_MS = 350;

/** Scenarios for Proof Wall */
const PROOF_SCENARIOS = [
  {
    id: "marketing",
    title: "Scenario 1: Vague Marketing Request",
    tag: "Marketing & Growth",
    rawInput: "email to client asking if they reviewed the proposal",
    genericOutput:
      "Subject: 🔥 URGENT: Did you see this game-changing proposal?! 🚀\n\nHey Rockstars! 👋\nHope you're having a 10x day! Just wanted to circle back and see if you had a quick 45 minutes to dive deep into our synergy-packed proposal. Opportunities like this don't stay open long! Don't let your competition steal your lunch. Click below now! 👇✨",
    genericFlaw: "Turns it into a 400-word pushy sales sequence with fake scarcity and emojis. (Cringe).",
    refinziMode: "Better Mode (⚡ Click)",
    refinziOutput:
      "Draft a concise follow-up email regarding the project proposal submitted on [Date].\n\nRequirements:\n- Professional, courteous, low-friction tone suitable for senior enterprise decision-makers.\n- Acknowledge their time constraints.\n- Ask specifically if they have questions on the scope or pricing structure.\n- Single clear Call to Action: Offer a 10-minute sync this Thursday or Friday to address open items.",
    refinziPraise: "Adds professional tone and a low-friction Call to Action. Sounds like a highly competent human account executive. (Nailed it).",
  },
  {
    id: "coding",
    title: "Scenario 2: Complex Coding Task",
    tag: "Engineering & Architecture",
    rawInput: "fix memory leak in node server",
    genericOutput:
      "Act as a world-class 10x ninja developer and fix the memory leak. As a seasoned veteran software architect with 25 years of cutting-edge experience, you must write clean, bug-free, scalable code. Always follow best practices, add extensive comments, and write elegant code...",
    genericFlaw: 'Fluffs prompt with "world-class ninja" prestige fluff without giving concrete diagnostic steps. (Useless fluff).',
    refinziMode: "Expert Mode (🧠 Hold)",
    refinziOutput:
      "Execution Directive: Diagnose and remediate Node.js process heap memory growth.\n\nDiagnostics & Profiling:\n1. Guide generation of V8 heap snapshots via --inspect and comparison in Chrome DevTools.\n2. Audit common Node.js retention vectors: unevicted LRU cache entries, global EventEmitters without removeListener, and lingering socket streams.\n3. Output minimal, isolated reproduction code demonstrating the leak and the patch.\n4. Verification: Provide a standalone k6 or autocannon benchmark script validating heap flatline under 5,000 req/sec load.",
    refinziPraise: "Locks scope to debugging. Demands V8 heap snapshots, checks unevicted caches, and requires automated load test verification. (Senior Engineer level).",
  },
];

export default function App() {
  const [pathname, setPathname] = useState(
    typeof window !== "undefined" ? window.location.pathname : "/"
  );

  useEffect(() => {
    const handlePopState = () => {
      setPathname(window.location.pathname);
    };
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  if (pathname.startsWith("/privacy")) {
    return <PrivacyPage />;
  }
  if (pathname.startsWith("/terms")) {
    return <TermsPage />;
  }
  if (pathname.startsWith("/docs")) {
    return <DocsPage />;
  }

  // --- Interactive States ---
  const [activePlatform, setActivePlatform] = useState("chatgpt");
  const [composerText, setComposerText] = useState(DEMO_INPUT);
  const [lastAction, setLastAction] = useState(null); // 'better' | 'expert' | null
  const [isHolding, setIsHolding] = useState(false);
  const [isExpertReady, setIsExpertReady] = useState(false);
  const [holdProgress, setHoldProgress] = useState(0);
  const [showUndo, setShowUndo] = useState(false);
  const [activeScenario, setActiveScenario] = useState("marketing");
  const [showCheckoutModal, setShowCheckoutModal] = useState(false);
  const [showExitModal, setShowExitModal] = useState(false);
  const [checkoutEmail, setCheckoutEmail] = useState("");
  const [checkoutStatus, setCheckoutStatus] = useState(null);
  const [exitEmail, setExitEmail] = useState("");
  const [exitStatus, setExitStatus] = useState(null);

  // --- Live Simulated Prompt Counter ---
  const [liveCounter, setLiveCounter] = useState(14208);
  useEffect(() => {
    const interval = setInterval(() => {
      setLiveCounter((prev) => prev + Math.floor(Math.random() * 2) + 1);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  // --- Exit Intent Trigger ---
  useEffect(() => {
    let triggered = false;
    const handleMouseLeave = (e) => {
      if (e.clientY <= 15 && !triggered && !sessionStorage.getItem("exit_intent_shown")) {
        triggered = true;
        sessionStorage.setItem("exit_intent_shown", "true");
        setShowExitModal(true);
      }
    };
    document.addEventListener("mouseleave", handleMouseLeave);
    return () => document.removeEventListener("mouseleave", handleMouseLeave);
  }, []);

  // --- Keyboard Shortcuts for Demo (<kbd>Ctrl+Z</kbd>) ---
  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z") {
        if (composerText !== DEMO_INPUT) {
          e.preventDefault();
          undoAction();
        }
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [composerText]);

  // --- Orb Pointer Refs & Handlers ---
  const holdTimer = useRef(null);
  const animFrame = useRef(null);
  const pointerStartTime = useRef(0);
  const isPointerDown = useRef(false);
  const didHold = useRef(false);
  const undoTimer = useRef(null);

  useEffect(() => {
    return () => {
      clearTimeout(holdTimer.current);
      clearTimeout(undoTimer.current);
      if (animFrame.current) cancelAnimationFrame(animFrame.current);
    };
  }, []);

  const flashUndo = () => {
    setShowUndo(true);
    clearTimeout(undoTimer.current);
    undoTimer.current = setTimeout(() => setShowUndo(false), 9000);
  };

  const applyBetter = () => {
    setComposerText(BETTER_OUTPUT);
    setLastAction("better");
    flashUndo();
  };

  const applyExpert = () => {
    setComposerText(EXPERT_OUTPUT);
    setLastAction("expert");
    flashUndo();
  };

  const undoAction = () => {
    setComposerText(DEMO_INPUT);
    setLastAction(null);
    setShowUndo(false);
  };

  const handlePointerDown = (e) => {
    if (e.button !== 0) return;
    e.preventDefault();
    isPointerDown.current = true;
    didHold.current = false;
    pointerStartTime.current = performance.now();
    setIsHolding(true);
    setIsExpertReady(false);
    setHoldProgress(0);

    const tick = (now) => {
      if (!isPointerDown.current) return;
      const elapsed = now - pointerStartTime.current;
      const progress = Math.min(1, elapsed / HOLD_MS);
      setHoldProgress(progress);
      if (progress >= 1) {
        setIsExpertReady(true);
        didHold.current = true;
      } else {
        animFrame.current = requestAnimationFrame(tick);
      }
    };
    animFrame.current = requestAnimationFrame(tick);
  };

  const handlePointerUp = () => {
    if (!isPointerDown.current) return;
    isPointerDown.current = false;
    if (animFrame.current) cancelAnimationFrame(animFrame.current);
    const elapsed = performance.now() - pointerStartTime.current;
    setIsHolding(false);
    setIsExpertReady(false);
    setHoldProgress(0);

    if (elapsed >= HOLD_MS || didHold.current) {
      applyExpert();
    } else {
      applyBetter();
    }
  };

  const handlePointerCancel = () => {
    isPointerDown.current = false;
    setIsHolding(false);
    setIsExpertReady(false);
    setHoldProgress(0);
    if (animFrame.current) cancelAnimationFrame(animFrame.current);
  };

  const scrollToPricing = () => {
    const el = document.getElementById("pricing");
    if (el) {
      el.scrollIntoView({ behavior: "smooth" });
    }
  };

  const handleCheckoutSubmit = (e) => {
    e.preventDefault();
    if (!checkoutEmail || !checkoutEmail.includes("@")) return;
    setCheckoutStatus("processing");
    setTimeout(() => {
      setCheckoutStatus("success");
    }, 1200);
  };

  const handleExitSubmit = (e) => {
    e.preventDefault();
    if (!exitEmail || !exitEmail.includes("@")) return;
    setExitStatus("success");
  };

  const selectedProof = PROOF_SCENARIOS.find((s) => s.id === activeScenario) || PROOF_SCENARIOS[0];

  return (
    <div className="min-h-screen bg-[#08090c] text-slate-100 selection:bg-indigo-600/30 selection:text-white font-sans antialiased">
      {/* ============================================================
          1. STICKY TOP BAR (THE PATTERN INTERRUPT)
          ============================================================ */}
      <aside aria-label="Urgency announcement" className="sticky top-0 z-50 bg-gradient-to-r from-rose-950/90 via-amber-950/90 to-rose-950/90 border-b border-rose-500/30 backdrop-blur-md px-3 py-2 text-center text-xs">
        <div className="max-w-6xl mx-auto flex flex-wrap items-center justify-center gap-2 sm:gap-3">
          <div className="flex items-center gap-1.5 font-black text-amber-300">
            <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" aria-hidden="true" />
            <span>WARNING:</span>
          </div>
          <span className="text-white font-medium">
            You are paying the &ldquo;Stupid Tax&rdquo; on every bad AI prompt. Stop spending 20 minutes fixing the AI&rsquo;s garbage output. Fix the prompt in 2 seconds instead.
          </span>
          <a
            href={DOWNLOADS.chrome}
            download
            className="inline-flex items-center gap-1 bg-amber-400 hover:bg-amber-300 text-black font-bold px-3 py-1 rounded-full text-[11px] shadow-md shadow-amber-500/20 transition-all shrink-0 ml-1"
          >
            <Download className="w-3 h-3" aria-hidden="true" />
            <span>Add to Chrome — Free</span>
          </a>
        </div>
      </aside>

      {/* ============================================================
          MAIN NAVIGATION
          ============================================================ */}
      <header className="border-b border-white/[0.06] bg-[#0C0D12]/80 backdrop-blur-xl sticky top-[37px] z-40">
        <nav aria-label="Main Navigation" className="max-w-6xl mx-auto px-4 h-14 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2.5" aria-label="Refinzi homepage">
            <span className="w-7 h-7 rounded-lg bg-gradient-to-tr from-indigo-600 to-emerald-400 flex items-center justify-center font-black text-white text-sm shadow-md shadow-indigo-500/20">
              R
            </span>
            <span className="font-extrabold text-white text-lg tracking-tight">Refinzi</span>
            <span className="text-[10px] font-bold text-emerald-400 bg-emerald-950/80 border border-emerald-500/30 px-2 py-0.5 rounded-full">
              2.1.0
            </span>
          </a>

          <ul className="hidden md:flex items-center gap-6 text-xs font-semibold text-slate-300">
            <li><a href="#mechanism" className="hover:text-white transition-colors">How It Works</a></li>
            <li><a href="#proof" className="hover:text-white transition-colors">Proof Wall</a></li>
            <li><a href="#pricing" className="hover:text-white transition-colors">Pricing</a></li>
            <li><a href="#faq" className="hover:text-white transition-colors">FAQ</a></li>
          </ul>

          <div className="flex items-center gap-3">
            <button
              onClick={scrollToPricing}
              className="hidden sm:inline-flex text-xs font-bold text-emerald-400 hover:text-emerald-300 transition-colors"
            >
              Lifetime Pro $12
            </button>
            <a
              href={DOWNLOADS.chrome}
              download
              className="rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs px-3.5 py-2 shadow-lg shadow-indigo-600/20 border border-indigo-400/30 inline-flex items-center gap-1.5 transition-all"
            >
              <Download className="w-3.5 h-3.5" aria-hidden="true" />
              <span>Add to Chrome</span>
            </a>
          </div>
        </nav>
      </header>

      <main id="main-content">
        {/* ============================================================
            2. ABOVE-THE-FOLD HERO (THE DREAM OUTCOME)
            ============================================================ */}
        <section className="relative pt-16 pb-16 md:pt-24 md:pb-20 overflow-hidden text-center">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_45%_at_50%_0%,rgba(99,102,241,0.18),transparent_70%)] pointer-events-none" />

          <div className="max-w-5xl mx-auto px-4 relative z-10">
            {/* Eyebrow Badge */}
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-indigo-500/30 bg-indigo-950/40 text-[11px] font-bold text-indigo-300 mb-6 uppercase tracking-wider shadow-inner">
              <Globe className="w-3.5 h-3.5 text-emerald-400" aria-hidden="true" />
              <span>THE UNIVERSAL BROWSER TEXT LAYER • MANIFEST V3 • 100% PRIVATE</span>
            </div>

            {/* Headline */}
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-white tracking-tight leading-[1.1] max-w-4xl mx-auto">
              Stop Babysitting Your AI.
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-sky-300 to-emerald-400 mt-1.5">
                Get Senior-Level Outputs on the First Try.
              </span>
            </h1>

            {/* Sub-headline */}
            <p className="mt-6 text-base sm:text-lg text-slate-300 max-w-3xl mx-auto leading-relaxed font-normal">
              You know what you want. The AI doesn&rsquo;t. Refinzi is the invisible calibration layer that lives in your browser. Type your messy thought. Click the Orb for instant structure. Hold the Orb for an expert brief.
            </p>

            <p className="mt-3 text-xs sm:text-sm font-semibold text-emerald-400 tracking-wide">
              No forms. No prompt engineering degrees. No questions asked.
            </p>

            {/* Primary & Secondary CTAs */}
            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-3.5">
              <a
                href={DOWNLOADS.chrome}
                download
                className="w-full sm:w-auto px-8 py-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-extrabold text-base shadow-xl shadow-indigo-600/30 border border-indigo-400/40 inline-flex items-center justify-center gap-2 transform hover:-translate-y-0.5 transition-all"
              >
                <Download className="w-5 h-5" aria-hidden="true" />
                <span>Add to Chrome — It&rsquo;s 100% Free</span>
              </a>

              <button
                onClick={scrollToPricing}
                className="w-full sm:w-auto px-7 py-4 rounded-xl bg-[#151620] hover:bg-[#1B1C28] text-emerald-400 hover:text-emerald-300 font-extrabold text-base border border-emerald-500/30 shadow-lg inline-flex items-center justify-center gap-2 transform hover:-translate-y-0.5 transition-all cursor-pointer"
              >
                <Zap className="w-5 h-5 text-amber-400" aria-hidden="true" />
                <span>Unlock Lifetime Pro — $12 (One-Time)</span>
              </button>
            </div>

            {/* Micro-copy */}
            <p className="mt-4 text-xs text-slate-400 font-medium">
              ⚡ Installs in 5 seconds • 🔒 Zero prompt logging • Works in ChatGPT, Claude, Gemini &amp; everywhere else.
            </p>

            {/* Live Social Proof / FOMO Ticker */}
            <div className="mt-8 inline-flex flex-wrap items-center justify-center gap-4 text-xs font-semibold px-5 py-2.5 rounded-2xl bg-[#12131D] border border-white/[0.08] shadow-inner">
              <div className="flex items-center gap-2 text-rose-400 font-mono">
                <Flame className="w-4 h-4 text-rose-500 animate-pulse" aria-hidden="true" />
                <span>{liveCounter.toLocaleString()} prompts calibrated today</span>
              </div>
              <span className="text-white/20" aria-hidden="true">•</span>
              <div className="flex items-center gap-1 text-amber-300">
                <div className="flex text-amber-400" aria-hidden="true">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-3.5 h-3.5 fill-amber-400" />
                  ))}
                </div>
                <span>4.9/5 from early access power-users</span>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================
            INTERACTIVE LIVE SIMULATOR + UNDO SAFETY NET
            ============================================================ */}
        <section aria-label="Interactive demo" className="max-w-4xl mx-auto px-4 -mt-4 mb-20 relative z-20">
          <div className="rounded-2xl border border-white/10 bg-[#12131C] shadow-2xl overflow-hidden backdrop-blur-md">
            {/* Header / Site Selector */}
            <div className="px-4 py-3 bg-[#0B0C11] border-b border-white/[0.06] flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-rose-500/80 inline-block" aria-hidden="true" />
                <span className="w-3 h-3 rounded-full bg-amber-500/80 inline-block" aria-hidden="true" />
                <span className="w-3 h-3 rounded-full bg-emerald-500/80 inline-block" aria-hidden="true" />
                <span className="text-xs text-slate-400 font-mono ml-2">Interactive In-Composer Demo</span>
              </div>

              <div className="flex items-center gap-1.5">
                {PLATFORMS.map((p) => (
                  <button
                    key={p.id}
                    onClick={() => setActivePlatform(p.id)}
                    className={`px-2.5 py-1 rounded text-[11px] font-semibold transition-all ${
                      activePlatform === p.id
                        ? "bg-indigo-600/30 text-indigo-300 border border-indigo-500/40"
                        : "text-slate-400 hover:text-white"
                    }`}
                  >
                    {p.name}
                  </button>
                ))}
              </div>
            </div>

            {/* Composer Input Surface */}
            <div className="p-5 sm:p-7 relative min-h-[220px] flex flex-col justify-between bg-[#13141E]">
              <div>
                <label className="text-[11px] uppercase tracking-wider text-slate-500 font-bold block mb-2">
                  Active Web Composer ({activePlatform})
                </label>
                <div className="text-sm font-mono whitespace-pre-wrap text-slate-200 leading-relaxed min-h-[110px]">
                  {composerText}
                </div>
              </div>

              {/* Floating Docked Orb with Click vs Hold Mechanics */}
              <div className="mt-4 pt-4 border-t border-white/[0.06] flex flex-wrap items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="relative">
                    <button
                      type="button"
                      onPointerDown={handlePointerDown}
                      onPointerUp={handlePointerUp}
                      onPointerCancel={handlePointerCancel}
                      className={`relative w-12 h-12 rounded-full flex items-center justify-center font-bold text-white shadow-xl select-none touch-none transition-transform cursor-pointer ${
                        isExpertReady
                          ? "bg-emerald-500 ring-4 ring-emerald-400/40 scale-110"
                          : isHolding
                          ? "bg-indigo-600 scale-95"
                          : "bg-indigo-600 hover:bg-indigo-500 hover:scale-105"
                      }`}
                      aria-label="Refinzi calibration orb. Click for Better, hold for Expert."
                      title="Click = ⚡ Better Prompt (< 350ms) | Hold = 🧠 Expert Brief (≥ 350ms)"
                    >
                      {/* SVG Charge Ring */}
                      <svg className="absolute inset-0 w-full h-full -rotate-90 pointer-events-none" viewBox="0 0 48 48">
                        <circle
                          cx="24"
                          cy="24"
                          r="21"
                          stroke="currentColor"
                          strokeWidth="3"
                          fill="none"
                          className="text-white/10"
                        />
                        <circle
                          cx="24"
                          cy="24"
                          r="21"
                          stroke="currentColor"
                          strokeWidth="3"
                          fill="none"
                          strokeDasharray={132}
                          strokeDashoffset={132 - 132 * holdProgress}
                          strokeLinecap="round"
                          className={isExpertReady ? "text-emerald-300" : "text-indigo-300"}
                        />
                      </svg>
                      {isExpertReady ? (
                        <Brain className="w-5 h-5 text-white animate-bounce" aria-hidden="true" />
                      ) : (
                        <Zap className="w-5 h-5 text-white" aria-hidden="true" />
                      )}
                    </button>
                  </div>

                  <div className="text-left">
                    <p className="text-xs font-bold text-white flex items-center gap-1.5">
                      <span>Refinzi Orb</span>
                      <span className="text-[10px] px-1.5 py-0.2 rounded bg-indigo-950 text-indigo-400 border border-indigo-500/20 font-mono">
                        {isExpertReady ? "EXPERT READY" : isHolding ? "CHARGING..." : "DOCK ACTIVE"}
                      </span>
                    </p>
                    <p className="text-[11px] text-slate-400">
                      <strong>Click</strong> for ⚡ Better • <strong>Press &amp; Hold</strong> for 🧠 Expert
                    </p>
                  </div>
                </div>

                {/* The Undo Safety Net Indicator */}
                <div className="flex items-center gap-2.5">
                  {showUndo && (
                    <button
                      onClick={undoAction}
                      className="px-3 py-1.5 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-bold text-xs inline-flex items-center gap-1.5 shadow-lg animate-fade-in transition-all"
                    >
                      <RotateCcw className="w-3.5 h-3.5" aria-hidden="true" />
                      <span>↩ Undo Calibration</span>
                    </button>
                  )}
                  <div className="text-right text-[11px] text-slate-400 font-mono">
                    <span>Press </span>
                    <kbd className="px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-200 border border-zinc-700">Ctrl</kbd>
                    <span> + </span>
                    <kbd className="px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-200 border border-zinc-700">Z</kbd>
                    <span> to undo anytime</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================
            3. THE AGITATION (TWISTING THE KNIFE)
            ============================================================ */}
        <section className="py-20 border-t border-white/[0.06] bg-[#0A0B10]">
          <div className="max-w-5xl mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto mb-14">
              <span className="text-xs font-bold uppercase tracking-widest text-rose-400">
                The Pain You Experience Daily
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold text-white mt-2 tracking-tight">
                The &ldquo;Prompt Engineering&rdquo; Lie is Costing You Hours Every Week.
              </h2>
              <p className="text-slate-400 text-sm sm:text-base mt-4 leading-relaxed">
                Right now, when you use AI, you are forced into two terrible choices:
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              {/* The Lazy Route */}
              <div className="p-7 rounded-2xl bg-[#12131C] border border-rose-500/20 flex flex-col justify-between relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-rose-500/5 rounded-full blur-2xl pointer-events-none" />
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="w-2.5 h-2.5 rounded-full bg-rose-400" />
                    <h3 className="font-extrabold text-white text-lg">Choice 1: The Lazy Route</h3>
                  </div>
                  <p className="text-slate-300 text-sm leading-relaxed mb-4">
                    You type a quick, vague prompt into ChatGPT or Claude. You get back a generic, robotic, fluffy answer that barely understands your context.
                  </p>
                  <p className="text-rose-400 text-xs font-mono font-semibold">
                    The Cost: 20+ minutes rewriting, arguing with the bot, and manually editing the output until it is barely usable.
                  </p>
                </div>
                <div className="mt-6 pt-4 border-t border-white/[0.06] text-xs text-slate-500 font-mono">
                  Result: Wasted time &amp; mediocre work.
                </div>
              </div>

              {/* The Mega-Prompt Route */}
              <div className="p-7 rounded-2xl bg-[#12131C] border border-amber-500/20 flex flex-col justify-between relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-amber-500/5 rounded-full blur-2xl pointer-events-none" />
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="w-2.5 h-2.5 rounded-full bg-amber-400" />
                    <h3 className="font-extrabold text-white text-lg">Choice 2: The Mega-Prompt Route</h3>
                  </div>
                  <p className="text-slate-300 text-sm leading-relaxed mb-4">
                    You spend 15 minutes writing a massive, 500-word prompt trying to explain role, tone, format, and edge cases.
                  </p>
                  <p className="text-amber-400 text-xs font-mono font-semibold">
                    The Cost: The AI hallucinates, ignores half your instructions, and builds an entire website when you only asked for a hero section.
                  </p>
                </div>
                <div className="mt-6 pt-4 border-t border-white/[0.06] text-xs text-slate-500 font-mono">
                  Result: Exhaustion &amp; prompt fatigue.
                </div>
              </div>
            </div>

            <div className="mt-10 p-6 rounded-2xl bg-indigo-950/20 border border-indigo-500/30 text-center max-w-3xl mx-auto">
              <p className="text-slate-200 text-sm sm:text-base font-medium">
                Both routes cost you time. And time is the only asset you can never buy back.
                <span className="block text-white font-bold mt-1 text-indigo-300">
                  Refinzi removes the friction. We don&rsquo;t just &ldquo;make prompts longer.&rdquo; We calibrate them for execution.
                </span>
              </p>
            </div>
          </div>
        </section>

        {/* ============================================================
            4. THE MECHANISM (HOW IT WORKS)
            ============================================================ */}
        <section id="mechanism" className="py-20 border-t border-white/[0.06]">
          <div className="max-w-5xl mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto mb-14">
              <span className="text-xs font-bold uppercase tracking-widest text-emerald-400">
                The 3-Second Workflow
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold text-white mt-2 tracking-tight">
                Never Ask. Infer → Assume → Execute.
              </h2>
              <p className="text-slate-400 text-sm sm:text-base mt-3 leading-relaxed">
                Refinzi reads your rough draft, understands your intent, and automatically injects the exact missing dimensions the AI needs to nail the job.
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              {/* Step 1: Click */}
              <div className="p-6 rounded-2xl bg-[#12131C] border border-white/[0.06] flex flex-col justify-between">
                <div>
                  <div className="w-10 h-10 rounded-xl bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400 font-bold mb-4">
                    <Zap className="w-5 h-5" aria-hidden="true" />
                  </div>
                  <h3 className="font-bold text-white text-base mb-1">
                    🖱️ CLICK THE ORB
                  </h3>
                  <span className="text-xs font-bold text-indigo-400 mb-3 inline-block">
                    ⚡ BETTER PROMPT (&lt; 350ms)
                  </span>
                  <p className="text-xs text-slate-300 leading-relaxed">
                    Instantly structures your thought. Adds the 1 to 3 critical missing constraints. Strips the fluff. Keeps your exact voice. Perfect for 90% of daily tasks.
                  </p>
                </div>
                <div className="mt-6 pt-4 border-t border-white/[0.06] text-[11px] font-mono text-emerald-400">
                  ✓ Instant 0-question transformation
                </div>
              </div>

              {/* Step 2: Hold */}
              <div className="p-6 rounded-2xl bg-[#12131C] border border-emerald-500/30 flex flex-col justify-between shadow-lg shadow-emerald-500/5">
                <div>
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400 font-bold mb-4">
                    <Brain className="w-5 h-5" aria-hidden="true" />
                  </div>
                  <h3 className="font-bold text-white text-base mb-1">
                    🖱️ HOLD THE ORB
                  </h3>
                  <span className="text-xs font-bold text-emerald-400 mb-3 inline-block">
                    🧠 EXPERT BRIEF (≥ 350ms)
                  </span>
                  <p className="text-xs text-slate-300 leading-relaxed">
                    Triggers deep, autonomous calibration. Locks the scope so the AI doesn&rsquo;t hallucinate extraneous bloat. Strips prestige jargon. Adds defensible assumptions.
                  </p>
                </div>
                <div className="mt-6 pt-4 border-t border-white/[0.06] text-[11px] font-mono text-emerald-400">
                  ✓ Senior practitioner task briefing
                </div>
              </div>

              {/* Step 3: Auto-apply */}
              <div className="p-6 rounded-2xl bg-[#12131C] border border-white/[0.06] flex flex-col justify-between">
                <div>
                  <div className="w-10 h-10 rounded-xl bg-sky-500/20 border border-sky-500/30 flex items-center justify-center text-sky-400 font-bold mb-4">
                    <CheckCircle2 className="w-5 h-5" aria-hidden="true" />
                  </div>
                  <h3 className="font-bold text-white text-base mb-1">
                    ✅ AUTO-APPLY
                  </h3>
                  <span className="text-xs font-bold text-sky-400 mb-3 inline-block">
                    DONE IN 2 SECONDS
                  </span>
                  <p className="text-xs text-slate-300 leading-relaxed">
                    The perfected prompt drops straight into your text box. Native Ctrl+Z undo stack remains intact. Hit enter. Get a masterpiece.
                  </p>
                </div>
                <div className="mt-6 pt-4 border-t border-white/[0.06] text-[11px] font-mono text-sky-400">
                  ✓ Zero copy-paste friction
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================
            5. THE "SHOW, DON'T TELL" PROOF WALL
            ============================================================ */}
        <section id="proof" className="py-20 border-t border-white/[0.06] bg-[#0A0B10]">
          <div className="max-w-5xl mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto mb-12">
              <span className="text-xs font-bold uppercase tracking-widest text-indigo-400">
                Show, Don&rsquo;t Tell
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold text-white mt-2 tracking-tight">
                See The Calibration Engine In Action
              </h2>
              <p className="text-slate-400 text-sm mt-3">
                See why Refinzi outputs perform materially better than generic AI prompt templates.
              </p>

              {/* Scenario Toggle */}
              <div className="mt-6 inline-flex p-1.5 rounded-xl bg-[#141520] border border-white/[0.08] gap-1">
                {PROOF_SCENARIOS.map((sc) => (
                  <button
                    key={sc.id}
                    onClick={() => setActiveScenario(sc.id)}
                    className={`px-4 py-2 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                      activeScenario === sc.id
                        ? "bg-indigo-600 text-white shadow"
                        : "text-slate-400 hover:text-white"
                    }`}
                  >
                    {sc.title}
                  </button>
                ))}
              </div>
            </div>

            {/* Proof Card */}
            <div className="rounded-2xl border border-white/[0.08] bg-[#12131C] p-6 sm:p-8">
              {/* Raw Input Bar */}
              <div className="p-4 rounded-xl bg-[#0C0D14] border border-white/[0.06] mb-6">
                <span className="text-[10px] font-mono font-bold uppercase text-slate-500 block mb-1">
                  Raw User Input
                </span>
                <p className="text-sm sm:text-base font-mono font-bold text-white">
                  &ldquo;{selectedProof.rawInput}&rdquo;
                </p>
              </div>

              {/* Head to Head Comparison */}
              <div className="grid md:grid-cols-2 gap-6">
                {/* ❌ Generic Enhancer */}
                <div className="p-5 rounded-xl bg-rose-950/10 border border-rose-500/20 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-2 mb-2 text-rose-400 font-bold text-xs uppercase tracking-wider">
                      <XCircle className="w-4 h-4 text-rose-400" aria-hidden="true" />
                      <span>❌ Generic AI &ldquo;Prompt Enhancer&rdquo;</span>
                    </div>
                    <p className="text-xs font-mono text-slate-300 whitespace-pre-wrap leading-relaxed">
                      {selectedProof.genericOutput}
                    </p>
                  </div>
                  <div className="mt-4 pt-3 border-t border-rose-500/20 text-xs text-rose-300 font-semibold">
                    {selectedProof.genericFlaw}
                  </div>
                </div>

                {/* ✅ Refinzi Calibrated */}
                <div className="p-5 rounded-xl bg-emerald-950/15 border border-emerald-500/30 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-2 mb-2 text-emerald-400 font-bold text-xs uppercase tracking-wider">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" aria-hidden="true" />
                      <span>✅ Refinzi ({selectedProof.refinziMode})</span>
                    </div>
                    <p className="text-xs font-mono text-slate-200 whitespace-pre-wrap leading-relaxed">
                      {selectedProof.refinziOutput}
                    </p>
                  </div>
                  <div className="mt-4 pt-3 border-t border-emerald-500/20 text-xs text-emerald-300 font-semibold">
                    {selectedProof.refinziPraise}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================
            6. THE GRAND SLAM OFFER (VALUE STACK & VISUAL RECEIPT)
            ============================================================ */}
        <section id="pricing" className="py-20 border-t border-white/[0.06] relative">
          <div className="max-w-5xl mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto mb-14">
              <span className="text-xs font-bold uppercase tracking-widest text-emerald-400">
                Zero Monthly Subscriptions
              </span>
              <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white mt-2 tracking-tight">
                Pay Once. Use It Forever.
              </h2>
              <p className="text-slate-400 text-sm sm:text-base mt-3 leading-relaxed">
                Software companies want to trap you in a $15/month subscription. We don&rsquo;t. Get the complete Refinzi Lifetime Pro Pass for less than the cost of a bad lunch.
              </p>
            </div>

            {/* Visual Receipt Graphic (Hormozi Style Value Stack) */}
            <div className="max-w-xl mx-auto rounded-3xl border border-white/15 bg-gradient-to-b from-[#141622] to-[#0D0E15] p-6 sm:p-8 shadow-2xl relative overflow-hidden">
              {/* Receipt Header */}
              <div className="flex items-center justify-between border-b border-white/[0.08] pb-5 mb-5">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
                    <Receipt className="w-5 h-5" aria-hidden="true" />
                  </div>
                  <div>
                    <h3 className="font-extrabold text-white text-base">Refinzi Lifetime Pro Pass</h3>
                    <p className="text-xs text-slate-400 font-mono">Invoice Summary • Zero Recurring Fees</p>
                  </div>
                </div>
                <span className="px-2.5 py-1 rounded-full bg-emerald-950 text-emerald-300 border border-emerald-500/30 text-[11px] font-bold">
                  PERPETUAL
                </span>
              </div>

              {/* Itemized Value Stack Rows */}
              <div className="space-y-3 text-xs sm:text-sm">
                <div className="flex items-center justify-between py-1 border-b border-white/[0.04]">
                  <span className="text-slate-300 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>The Core Calibration Engine (Click for Better)</span>
                  </span>
                  <span className="font-mono text-slate-400 font-semibold">$97 Value</span>
                </div>

                <div className="flex items-center justify-between py-1 border-b border-white/[0.04]">
                  <span className="text-slate-300 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>The Expert Scope-Lock Engine (Hold for Expert)</span>
                  </span>
                  <span className="font-mono text-slate-400 font-semibold">$197 Value</span>
                </div>

                <div className="flex items-center justify-between py-1 border-b border-white/[0.04]">
                  <span className="text-slate-300 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>Anti-Prestige Jargon Filter (No AI slop)</span>
                  </span>
                  <span className="font-mono text-slate-400 font-semibold">$47 Value</span>
                </div>

                <div className="flex items-center justify-between py-1 border-b border-white/[0.04]">
                  <span className="text-slate-300 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>Local-First Privacy Vault (Zero server logs)</span>
                  </span>
                  <span className="font-mono text-emerald-400 font-bold">Priceless</span>
                </div>

                <div className="flex items-center justify-between py-1 border-b border-white/[0.04]">
                  <span className="text-slate-300 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>BYOK Support (Direct provider HTTPS, 0% markup)</span>
                  </span>
                  <span className="font-mono text-slate-400 font-semibold">$97 Value</span>
                </div>

                <div className="flex items-center justify-between py-1">
                  <span className="text-slate-300 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>Lifetime Updates &amp; Site Adapters</span>
                  </span>
                  <span className="font-mono text-slate-400 font-semibold">$147/yr Value</span>
                </div>
              </div>

              {/* Receipt Total Calculation */}
              <div className="mt-6 pt-5 border-t border-dashed border-white/20">
                <div className="flex items-center justify-between text-xs text-slate-400 mb-1">
                  <span>TOTAL REAL VALUE</span>
                  <span className="line-through text-rose-400 font-mono text-sm font-bold">$585+</span>
                </div>
                <div className="flex items-center justify-between text-xs text-slate-400 mb-3">
                  <span>EARLY ACCESS DISCOUNT</span>
                  <span className="text-emerald-400 font-mono font-bold">-98% OFF</span>
                </div>
                <div className="flex items-baseline justify-between pt-2 border-t border-white/[0.08]">
                  <span className="font-bold text-white text-base">YOUR PRICE TODAY:</span>
                  <div className="text-right">
                    <span className="text-4xl sm:text-5xl font-black text-emerald-400 tracking-tight font-mono">
                      $12
                    </span>
                    <span className="block text-[10px] text-slate-400 font-mono">One-time payment • Never increases</span>
                  </div>
                </div>
              </div>

              {/* Checkout Action Button */}
              <button
                onClick={() => setShowCheckoutModal(true)}
                className="w-full mt-6 py-4 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-extrabold text-base shadow-xl shadow-emerald-500/25 transition-all transform hover:-translate-y-0.5 cursor-pointer flex items-center justify-center gap-2"
              >
                <Zap className="w-5 h-5" aria-hidden="true" />
                <span>⚡ Get Lifetime Pro for $12 Now</span>
              </button>

              <p className="mt-3 text-center text-[11px] text-slate-400">
                Instant license key delivery • Zero subscription lock-in • 14-day money back guarantee
              </p>
            </div>
          </div>
        </section>

        {/* ============================================================
            7. THE "NO-BRAINER" GUARANTEE (RISK REVERSAL)
            ============================================================ */}
        <section className="py-16 border-t border-white/[0.06] bg-[#0B0C12]">
          <div className="max-w-4xl mx-auto px-4">
            <div className="p-8 sm:p-10 rounded-3xl bg-[#12131D] border border-emerald-500/30 flex flex-col sm:flex-row items-center gap-6 sm:gap-8 shadow-2xl">
              <div className="w-16 h-16 rounded-2xl bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400 shrink-0">
                <ShieldCheck className="w-9 h-9" aria-hidden="true" />
              </div>
              <div className="text-center sm:text-left">
                <span className="text-xs font-bold uppercase tracking-widest text-emerald-400">
                  100% Risk Reversal
                </span>
                <h3 className="text-2xl sm:text-3xl font-extrabold text-white mt-1">
                  The &ldquo;10-Hour&rdquo; Iron-Clad Guarantee
                </h3>
                <p className="text-slate-300 text-xs sm:text-sm mt-3 leading-relaxed">
                  Add Refinzi to your browser. Use the Pro features for 14 full days. If it doesn&rsquo;t save you at least 10 hours of wasted tweaking, rewriting, and AI-babysitting... send us a one-line email. We will refund your $12 immediately. No questions asked. No hard feelings.
                </p>
                <p className="text-emerald-400 text-xs font-bold mt-2">
                  You take zero risk. We take all of it.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================
            8. OBJECTION CRUSHING (FAQ)
            ============================================================ */}
        <section id="faq" className="py-20 border-t border-white/[0.06] bg-[#0A0B10]">
          <div className="max-w-4xl mx-auto px-4">
            <div className="text-center max-w-2xl mx-auto mb-14">
              <span className="text-xs font-bold uppercase tracking-widest text-indigo-400">
                Questions Answered
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold text-white mt-2">
                Frequently Asked Questions
              </h2>
            </div>

            <div className="space-y-4">
              <div className="p-6 rounded-2xl bg-[#13141F] border border-white/[0.06]">
                <h3 className="font-extrabold text-white text-base mb-2">
                  Is my data private? Are you reading my prompts?
                </h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  <strong>100% Local-First.</strong> Refinzi processes your text locally in your browser. We do not log, store, or train on your prompts. If you use our cloud engine, it is ephemeral. If you use BYOK, it connects directly from your browser to your provider over HTTPS.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#13141F] border border-white/[0.06]">
                <h3 className="font-extrabold text-white text-base mb-2">
                  Will this slow down my browser?
                </h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  <strong>Nope.</strong> Refinzi is built on Manifest V3. It sits quietly in the background and only wakes up when you interact with an editable text box. It uses minimal memory and zero battery-draining polling.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#13141F] border border-white/[0.06]">
                <h3 className="font-extrabold text-white text-base mb-2">
                  Do I need to pay for ChatGPT Plus to use this?
                </h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  <strong>No.</strong> Refinzi works beautifully with the free tiers of AI tools. If you have Plus or Pro, it makes those models perform 10x better by feeding them calibrated directives instead of ambiguous thoughts.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#13141F] border border-white/[0.06]">
                <h3 className="font-extrabold text-white text-base mb-2">
                  Is the $12 really a one-time payment?
                </h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  <strong>Yes.</strong> We are doing this to build a massive, loyal user base quickly. Once we hit our capacity cap, this switches to a standard yearly subscription. Lock in your lifetime access today.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ============================================================
            9. FINAL CTA (THE CLOSE)
            ============================================================ */}
        <section className="py-24 border-t border-white/[0.06] text-center relative overflow-hidden">
          <div className="max-w-4xl mx-auto px-4 relative z-10">
            <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
              Stop Settling for Mediocre AI Outputs.
            </h2>
            <p className="mt-4 text-slate-300 text-sm sm:text-base max-w-2xl mx-auto leading-relaxed">
              Join thousands of creators, coders, and founders who get it right on the first try.
            </p>

            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
              <a
                href={DOWNLOADS.chrome}
                download
                className="w-full sm:w-auto px-8 py-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-extrabold text-base shadow-xl shadow-indigo-600/30 border border-indigo-400/40 inline-flex items-center justify-center gap-2 transform hover:-translate-y-0.5 transition-all"
              >
                <Download className="w-5 h-5" aria-hidden="true" />
                <span>Add to Chrome — Free</span>
              </a>

              <button
                onClick={scrollToPricing}
                className="w-full sm:w-auto px-8 py-4 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-extrabold text-base shadow-xl shadow-emerald-500/20 inline-flex items-center justify-center gap-2 transform hover:-translate-y-0.5 transition-all cursor-pointer"
              >
                <Zap className="w-5 h-5" aria-hidden="true" />
                <span>Get Lifetime Pro ($12)</span>
              </button>
            </div>

            <div className="mt-6 flex flex-wrap items-center justify-center gap-4 text-xs text-slate-400">
              <span>Setup takes 5 seconds.</span>
              <span aria-hidden="true">•</span>
              <span>Works on Mac, Windows, and Linux.</span>
              <span aria-hidden="true">•</span>
              <a href={DOWNLOADS.firefox} download className="hover:text-white underline">
                Firefox Add-on
              </a>
              <span aria-hidden="true">•</span>
              <a href={DOWNLOADS.edge} download className="hover:text-white underline">
                Edge Add-on
              </a>
            </div>
          </div>
        </section>
      </main>

      {/* ============================================================
          FOOTER
          ============================================================ */}
      <footer className="border-t border-white/[0.06] py-10 bg-[#07080C]">
        <div className="max-w-6xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-slate-500">
            Refinzi 2.1.0 • &ldquo;Better prompts in one click. Expert prompts when it matters.&rdquo; • Open Source MIT
          </p>
          <nav aria-label="Footer legal navigation" className="flex flex-wrap items-center justify-center gap-4 text-xs">
            <a href="/privacy/" className="text-slate-400 hover:text-white underline">Privacy Policy</a>
            <a href="/terms/" className="text-slate-400 hover:text-white underline">Terms of Service</a>
            <a href="/docs/" className="text-slate-400 hover:text-white underline">Documentation</a>
            <a
              href="https://github.com/papada1472/refinzi"
              target="_blank"
              rel="noopener noreferrer"
              className="text-slate-400 hover:text-white underline"
            >
              GitHub Repository
            </a>
          </nav>
        </div>
      </footer>

      {/* ============================================================
          CHECKOUT MODAL (FRICTIONLESS $12 PRO PASS)
          ============================================================ */}
      {showCheckoutModal && (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="checkout-modal-title"
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in"
        >
          <div className="relative w-full max-w-md rounded-2xl border border-white/15 bg-[#12141E] p-6 sm:p-7 shadow-2xl">
            <button
              onClick={() => {
                setShowCheckoutModal(false);
                setCheckoutStatus(null);
              }}
              className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-white bg-white/5 hover:bg-white/10 transition-colors"
              aria-label="Close checkout modal"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="text-center mb-6">
              <div className="w-12 h-12 rounded-2xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400 mx-auto mb-3">
                <Zap className="w-6 h-6" />
              </div>
              <h3 id="checkout-modal-title" className="text-xl font-extrabold text-white">
                Unlock Lifetime Pro Pass
              </h3>
              <p className="text-xs text-slate-400 mt-1">
                One-time payment of <strong>$12</strong>. No subscriptions. Delivered instantly.
              </p>
            </div>

            {checkoutStatus === "success" ? (
              <div className="p-5 rounded-xl bg-emerald-950/40 border border-emerald-500/40 text-center space-y-3">
                <CheckCircle2 className="w-8 h-8 text-emerald-400 mx-auto" />
                <p className="text-sm font-bold text-white">Order Confirmed!</p>
                <p className="text-xs text-slate-300">
                  Your Pro License Key and activation instructions have been sent to{" "}
                  <strong className="text-emerald-300">{checkoutEmail}</strong>.
                </p>
                <button
                  onClick={() => setShowCheckoutModal(false)}
                  className="w-full mt-2 py-2.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-black font-bold text-xs"
                >
                  Done
                </button>
              </div>
            ) : (
              <form onSubmit={handleCheckoutSubmit} className="space-y-4">
                <div>
                  <label htmlFor="checkout-email-input" className="block text-xs font-bold text-slate-300 mb-1.5">
                    Where should we send your License Key?
                  </label>
                  <input
                    id="checkout-email-input"
                    type="email"
                    required
                    value={checkoutEmail}
                    onChange={(e) => setCheckoutEmail(e.target.value)}
                    placeholder="you@company.com"
                    className="w-full px-4 py-3 rounded-xl bg-[#090A10] border border-white/10 text-white placeholder:text-slate-600 text-xs focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"
                  />
                </div>

                <div className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] text-[11px] text-slate-400 space-y-1">
                  <div className="flex justify-between text-white font-semibold">
                    <span>Refinzi Pro Perpetual License</span>
                    <span className="font-mono text-emerald-400">$12.00</span>
                  </div>
                  <div>Zero account registration required • 3-click checkout</div>
                </div>

                <button
                  type="submit"
                  disabled={checkoutStatus === "processing"}
                  className="w-full py-3.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-extrabold text-sm shadow-xl shadow-emerald-500/20 transition-all cursor-pointer disabled:opacity-50"
                >
                  {checkoutStatus === "processing" ? "Processing..." : "Complete Order ($12)"}
                </button>

                <p className="text-[10px] text-center text-slate-500">
                  🔒 256-bit encrypted checkout • 14-day 10-hour guarantee
                </p>
              </form>
            )}
          </div>
        </div>
      )}

      {/* ============================================================
          EXIT INTENT POPUP (GROWTH HACKER PLAYBOOK)
          ============================================================ */}
      {showExitModal && (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="exit-modal-title"
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in"
        >
          <div className="relative w-full max-w-md rounded-2xl border border-indigo-500/30 bg-[#12141F] p-6 sm:p-7 shadow-2xl">
            <button
              onClick={() => setShowExitModal(false)}
              className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-white bg-white/5 hover:bg-white/10 transition-colors"
              aria-label="Close free template popup"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="text-center mb-5">
              <span className="text-[10px] font-bold uppercase tracking-widest text-amber-400 bg-amber-950/60 border border-amber-500/30 px-2.5 py-0.5 rounded-full inline-block mb-3">
                Wait! Free Resource Before You Go
              </span>
              <h3 id="exit-modal-title" className="text-xl font-extrabold text-white">
                Grab Our 50 Expert Prompt Frameworks
              </h3>
              <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                Get our curated Notion swipe file with 50 senior-level prompt specifications for coding, strategy, and marketing. 100% free.
              </p>
            </div>

            {exitStatus === "success" ? (
              <div className="p-4 rounded-xl bg-emerald-950/40 border border-emerald-500/40 text-center space-y-2">
                <CheckCircle2 className="w-7 h-7 text-emerald-400 mx-auto" />
                <p className="text-xs font-bold text-white">Swipe File Sent!</p>
                <p className="text-[11px] text-slate-300">
                  Check your inbox for the Notion template link.
                </p>
              </div>
            ) : (
              <form onSubmit={handleExitSubmit} className="space-y-3">
                <input
                  type="email"
                  required
                  value={exitEmail}
                  onChange={(e) => setExitEmail(e.target.value)}
                  placeholder="Enter your email address"
                  className="w-full px-4 py-3 rounded-xl bg-[#090A10] border border-white/10 text-white placeholder:text-slate-600 text-xs focus:outline-none focus:border-indigo-500"
                />
                <button
                  type="submit"
                  className="w-full py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-600/25 transition-all cursor-pointer"
                >
                  Send Me The 50 Frameworks
                </button>
              </form>
            )}
          </div>
        </div>
      )}
    </div>
  );
}